[package]
name = "usda-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "3.0.0-rc4"
serde = { workspace = true }
hex = { workspace = true }
ed25519-dalek = "2.0"
sha2 = "0.10"
thiserror = "1.0"
serde_arrays = "0.1"
bincode = "1.3"

[dev-dependencies]
rand = "0.8"
